apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ./dev-shortener-config.yaml
- ../../base/shortener/
patches:
- path: ./dev-shortener-patch-deploy.yaml
- path: ./dev-shortener-patch-service.yaml
images:
- name: shortener-api-image
  newName: shortener-api
  newTag: "0.1.0"
