apiVersion: v1
kind: Namespace
metadata:
  name: shortener-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: shortener-system
spec:
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: shortener-api
        image: shortener-api-image
        ports:
        - name: shortener-api
          containerPort: 3000
        - name: shortener-debug
          containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: shortener-service
  namespace: shortener-system
